version: '3.1'

services:
  web:
    container_name: apache
    image: apache_php_sitecreator
    restart: always
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/app"

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: haslohaslo123
    ports:
      - "3306:3306"
    volumes:
      - db-vol:/var/lib/mariadb
      - ./installDir/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"

volumes:
  db-vol:
  db:
    driver: local